WARNING 10/Jan/2024 12:47:29 basehttp 29800 23676 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 12:56:28 basehttp 56872 19580 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:03:27 basehttp 56872 34208 "GET /media/tool_images/pecvd.jpeg HTTP/1.1" 404 33260
WARNING 10/Jan/2024 13:13:24 basehttp 56872 29588 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:13:54 basehttp 56872 34208 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:14:18 basehttp 56872 30116 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:21:03 basehttp 56872 2204 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:22:50 basehttp 56872 34208 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:23:37 basehttp 56872 47308 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:23:50 basehttp 56872 26560 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:23:56 basehttp 56872 2204 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:25:47 basehttp 56872 30116 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:26:46 basehttp 56872 47308 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 10/Jan/2024 13:27:23 basehttp 56872 2204 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 16/Jan/2024 14:29:34 basehttp 19320 9088 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 16/Jan/2024 14:30:41 basehttp 19320 24312 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 16/Jan/2024 14:30:56 basehttp 19320 17392 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 16/Jan/2024 14:48:07 basehttp 9932 57336 "GET /media/tool_images/pecvd.jpeg HTTP/1.1" 404 33260
WARNING 17/Jan/2024 12:52:55 basehttp 25100 43272 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 17/Jan/2024 12:58:23 basehttp 25100 36316 "GET /favicon.ico HTTP/1.1" 404 41058
WARNING 17/Jan/2024 14:40:19 basehttp 25100 20496 "GET /media/tool_images/pecvd.jpeg HTTP/1.1" 404 33260
WARNING 17/Jan/2024 14:43:30 basehttp 25100 10124 "POST /enable_tool/4/user/1/project/2/staff_charge/false/ HTTP/1.1" 400 83
WARNING 17/Jan/2024 14:43:41 basehttp 25100 10124 "POST /enable_tool/4/user/1/project/2/staff_charge/false/ HTTP/1.1" 400 83
WARNING 18/Jan/2024 12:11:22 basehttp 45380 3996 "POST /enable_tool/63/user/1/project/2/staff_charge/false/ HTTP/1.1" 400 83
WARNING 18/Jan/2024 13:27:13 basehttp 25388 32452 "GET /favicon.ico HTTP/1.1" 404 41058
ERROR 18/Jan/2024 13:30:06 log 25388 12156 Internal Server Error: /kiosk/enable_tool/
Traceback (most recent call last):
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\NEMO\apps\kiosk\views.py", line 36, in enable_tool
    return do_enable_tool(request, request.POST["tool_id"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\NEMO\decorators.py", line 67, in decorator
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\NEMO\apps\kiosk\views.py", line 43, in do_enable_tool
    project = Project.objects.get(id=request.POST["project_id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\sql\query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\sql\query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\sql\query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\sql\query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\laytonc\NEMO\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got ''.
ERROR 18/Jan/2024 13:30:06 basehttp 25388 12156 "POST /kiosk/enable_tool/ HTTP/1.1" 500 164958
